name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt -y update
          sudo apt -y install git golang liblzma-dev

      - uses: actions/checkout@v4

      - name: Build
        run: go mod download github.com/golang/protobuf && go mod download golang.org/x/exp && go mod download github.com/xi2/xz && go mod download github.com/ulikunitz/xz && go mod download github.com/pkg/errors && go mod download github.com/modern-go/reflect2 && go mod download github.com/modern-go/concurrent && go mod download github.com/klauspost/compress && go build .

