name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt -y update
          sudo apt -y install git golang liblzma-dev

      - uses: actions/checkout@v4

      - name: Build
        run: go build .

